# Generated by Django 4.1.6 on 2023-02-07 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="wight",
            new_name="weight",
        ),
    ]
