# Generated by Django 4.0.5 on 2023-02-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_alter_pet_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pets',
            field=models.ManyToManyField(related_name='traits', to='pets.pet'),
        ),
    ]
