# Generated by Django 4.0.5 on 2023-02-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0005_remove_trait_pets'),
        ('pets', '0014_pet_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pets',
        ),
        migrations.AddField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='traits', to='traits.trait'),
        ),
    ]
