# Generated by Django 4.0.5 on 2023-02-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0005_remove_trait_pets'),
        ('pets', '0015_remove_pet_pets_pet_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='pets', to='traits.trait'),
        ),
    ]
