# Generated by Django 4.0.5 on 2023-02-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0007_alter_trait_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='trait_name',
            new_name='name',
        ),
    ]
