# Generated by Django 4.0.5 on 2023-02-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0009_rename_name_trait_trait_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='trait_name',
            new_name='name',
        ),
    ]
